# Generated by Django 5.2.5 on 2025-10-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apartment_number_of_tenants_apartment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='accounts.tenant'),
        ),
    ]
