# Generated by Django 5.2.5 on 2025-10-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bill_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='visitors_charge',
        ),
    ]
