# Generated by Django 5.2.5 on 2025-10-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_bill_visitors_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.bill'),
        ),
    ]
